# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170730_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
